# Generated by Django 5.0 on 2024-02-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_alter_cartitems_options_alter_maxsulot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maxsulot',
            options={'ordering': ['-ball'], 'verbose_name_plural': 'Maxsulotlar'},
        ),
        migrations.AddField(
            model_name='maxsulot',
            name='ball',
            field=models.BigIntegerField(default=1),
        ),
    ]
