# Generated by Django 5.0 on 2024-06-11 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_kategoriya'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxsulot',
            name='kategoriya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.kategoriya'),
        ),
    ]
