# Generated by Django 5.0 on 2024-06-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_maxsulot_kategoriya'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kimga',
            field=models.CharField(blank=True, choices=[('1', "Mexanika bo'limi"), ('2', 'Omborxona')], max_length=255, null=True),
        ),
    ]
