# Generated by Django 5.0 on 2025-01-03 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0011_department_kategoriya_image_maxsulot_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriya',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.department'),
        ),
    ]
