# Generated by Django 4.2.17 on 2025-01-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0012_kategoriya_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriya',
            name='nomi_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kategoriya',
            name='nomi_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maxsulot',
            name='nomi_ru',
            field=models.CharField(max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='maxsulot',
            name='nomi_uz',
            field=models.CharField(max_length=455, null=True),
        ),
    ]
