# Generated by Django 5.1.5 on 2025-01-31 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0014_alter_kategoriya_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maxsulot',
            options={'verbose_name_plural': 'Maxsulotlar'},
        ),
        migrations.RemoveField(
            model_name='maxsulot',
            name='ball',
        ),
    ]
