# Generated by Django 5.1.5 on 2025-01-31 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0015_alter_maxsulot_options_remove_maxsulot_ball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoriya',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.department', verbose_name="Bo'lim"),
        ),
    ]
