# Generated by Django 5.1.5 on 2025-02-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0016_alter_kategoriya_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Buyurtma berildi'), ('2', 'Bajarildi'), ('3', 'Bekor qilindi'), ('4', 'Yetkazib berildi')], default='1', max_length=255, null=True),
        ),
    ]
