# Generated by Django 5.1.5 on 2025-02-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0018_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxsulot',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
