# Generated by Django 5.1.5 on 2025-02-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0019_maxsulot_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxsulot',
            name='razmer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
