# Generated by Django 5.1.5 on 2025-02-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0020_alter_maxsulot_razmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxsulot',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='maxsulotlar'),
        ),
    ]
