# Generated by Django 5.1.5 on 2025-02-14 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0021_alter_maxsulot_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxsulot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
