# Generated by Django 5.0 on 2023-12-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
