# Generated by Django 5.0 on 2023-12-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name_plural': 'Sayt sozlamalari'},
        ),
    ]
