# Generated by Django 5.1.5 on 2025-01-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_alter_adminparol_options_adminparol_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminparol',
            options={'ordering': ['section'], 'verbose_name': 'Admin Parol', 'verbose_name_plural': 'Admin Parollari'},
        ),
    ]
